--  TODO: (vsedov) (17:37:21 - 22/06/23): refactor this into null-ls config instead
local container = {
    null_ls = {
        diagnostic = {
            "cppcheck",
            "djlint",
            "eslint_d",
            "golangci_lint",
            "ktlint",
            "markdownlint",
            "misspell",
            "phpcs",
            "staticcheck",
            "stylelint",
            "write_good",
            "luacheck",
        },
        formatter = {
            "scalafmt",
            "stylish_haskell",
            "djlint",
            "fish_indent",
            "ktlint",
            "markdownlint",
            "phpcbf",
            "pint",
            "prettierd",
            "shellharden",
            "shfmt",
            "stylelint",
            "stylua",
            -- "trim_newlines",
            -- "trim_whitespace",
            "pyflyby",
            "latexindent",
        },
        code_action = { "eslint_d", "gitrebase", "refactoring" },
    },
}
return container
