
[treesitter]
auto_highlight = "all"
auto_install = "prompt"
# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!

[plugins]
"rocks.nvim" = "2.44.0"
"rocks-config.nvim" = "3.1.0"
"nvim-spider" = "scm"
"rocks-lazy.nvim" = "1.2.0"
"lspkind.nvim" = "scm"
nvim-notify = "scm"
friendly-snippets = "scm"
nvim-lspconfig = "1.7.0"
"mason-lspconfig.nvim" = "scm"
"mason.nvim" = "scm"
"better-escape.nvim" = {version= "scm", opt = true}
"actions-preview.nvim" = {version= "scm", opt = true}
"inc-rename.nvim" = {version= "scm", opt = true}
treesj = {version= "scm", opt = true}
"dial.nvim" = {version= "scm", opt = true}
"comment-box.nvim" = "scm"
"comment.nvim" = {version= "scm", opt = true}
"flash.nvim" = {version= "scm", opt = true}
"mini.visits" = "scm"
"dropbar.nvim" = "12.0.2"
"fidget.nvim" = "1.6.0"
"indent-blankline.nvim" = "scm"
nvim-web-devicons = "0.100"
"nui.nvim" = "0.3.0"
"oil.nvim" = "scm"
"bufdelete.nvim" = "scm"
nvim-nio = "1.7.0"
"image.nvim" = "1.3.0"
"rocks-dev.nvim" = "1.7.0"
"glow.nvim" = "0.2.0"
toml = "0.4.1"
luv = "1.50.0"
luasnip = "2.3.0"
"plenary.nvim" = "scm"
lzn-auto-require = "0.2.0"
nvim-autopairs = "scm"
nvim-surround = "3.1.0"
"rainbow-delimiters.nvim" = "scm"
"toggleterm.nvim" = "scm"
"yanky.nvim" = "scm"
"telescope-zf-native.nvim" = "1.0.0"
cmp_luasnip = {version= "scm" }
"substitute.nvim" = "scm"
nvim-various-textobjs = "scm"
"guess-indent.nvim" = "scm"
"smart-splits.nvim" = "scm"
"dressing.nvim" = "scm"
"none-ls-extras.nvim" = "scm"
"logging.nvim" = "1.1.0"
nvim-ufo = "1.4.0"
"yazi.nvim" = "10.0.1"
"telescope.nvim" = "scm"
"sqlite.lua" = "scm"
nvim-dap = "scm"
"iswap.nvim" = "scm"
"overseer.nvim" = "scm"
tree-sitter-python = "scm"
tree-sitter-toml = "scm"
tree-sitter-lua = "scm"
"rocks-git.nvim" = "2.5.3"
"rocks-treesitter.nvim" = "scm"
tree-sitter-latex = "scm"
neorg-se = "1.1.10"
"trouble.nvim" = "3.7.1"
nvim-jqx= "0.1.4"
"avante.nvim"= "0.0.23"
tree-sitter-fish = "0.0.30"
"edgy.nvim" = "1.10.2"

[plugins.neorg-interim-ls ]
version = "2.1.1"
opt = true

[plugins.neorg ]
version = "9.3.0"
opt = true

[plugins."render-markdown.nvim"]
version = "8.2.0"
opt = true

[plugins.promise-async ]
version = "scm"
opt = true

[plugins."cybu.nvim" ]
git = "ghillb/cybu.nvim"
rev = "v1.0"
opt = true

[plugins.nvim-window-picker ]
version = "2.4.0"

[plugins."neotab.nvim"]
git = "kawre/neotab.nvim"
rev = "f6ed1ef49f32586f5db95edae5d6f264c8180d85"

[plugins."garbage-day.nvim"]
git = "zeioth/garbage-day.nvim"
rev = "v1.3.1"
opt = true

[plugins.lsp-command]
git = "ii14/lsp-command"
rev = "b2d130d0358f7d64cd967c918182bce25944737b"

[plugins.luasnip-snippets]
git = "mireq/luasnip-snippets"
rev = "0.1.2"

[plugins."bufex.nvim"]
git = "tomiis4/bufex.nvim"
rev = "b7a3f8d610f383f3b28ffb6e7ebdb6bd1deb56e3"

[plugins.nvim-conda]
git = "kmontocam/nvim-conda"
rev = "v0.2.1"

[plugins."requirements.txt.vim"]
git = "raimon49/requirements.txt.vim"
rev = "v-1.9.0"

[plugins.neorg-templates-draft]
git = "pysan3/neorg-templates-draft"
rev = "v2.0.3"

[plugins.neorg-telescope]
git = "nvim-neorg/neorg-telescope"
rev = "v1.2.3"

[plugins."arrow.nvim"]
git = "otavioschwanck/arrow.nvim"
rev = "6e0f726f55f99332dd726a53effd6813786b6d49"
opt = true

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.16"

[plugins.vim-rooter]
git = "airblade/vim-rooter"
rev = "51402fb77c4d6ae94994e37dc7ca13bec8f4afcc"

[plugins."nui-components.nvim"]
git = "grapp-dev/nui-components.nvim"
rev = "v1.5.3"

[plugins."refgo.nvim"]
git = "prichrd/refgo.nvim"
rev = "5e8b4ef4536998d7611010e6dc7fbab131bc22ad"

[plugins.nvim-docs-view]
git = "amrbashir/nvim-docs-view"
rev = "f674ba57349849bce894efdd54096483c88e810b"
opt = true

[plugins.vim-devdocs]
git = "romainl/vim-devdocs"
rev = "85a98b86043ac6b4484663d75729e1b5bcebedbe"

[plugins."browse.nvim"]
git = "lalitmee/browse.nvim"
rev = "1ccf8705668216d8a311d31e87246b494b8eb571"

[plugins."wtf.nvim"]
git = "piersolenski/wtf.nvim"
rev = "22dac666c8847c9cb03afe99229d459f1d0822c4"

[plugins."compiler-explorer.nvim"]
git = "krady21/compiler-explorer.nvim"
rev = "ee8e7a2808bdad67cd2acb61b5c9ffa7735c7ec9"

[plugins."officer.nvim"]
git = "pianocomposer321/officer.nvim"
rev = "60b046e1068081d965f36fa8d728d6f2bc41ab77"

[plugins."compiler.nvim"]
git = "zeioth/compiler.nvim"
rev = "v3.3.9"
opt = true

[plugins."quicker.nvim"]
git = "stevearc/quicker.nvim"
rev = "v1.4.0"
[plugins."suda.vim"]
git = "lambdalisue/suda.vim"
rev = "v1.2.4"

[plugins."capslock.nvim"]
git = "barklan/capslock.nvim"
rev = "v1.4.1"
#
[plugins.vim-startuptime]
git = "dstein64/vim-startuptime"
rev = "v4.5.0"

[plugins.nvim-genghis]
git = "chrisgrieser/nvim-genghis"
rev = "466bdbbf64f14e03ea407c8ecec7a98b620e9d62"

[plugins.nvim-fundo]
git = "kevinhwang91/nvim-fundo"
rev = "ac9c9372c4bf677721e24f144ef29d3a05c2b589"
opt = true

[plugins."gitignore.nvim"]
git = "wintermute-cell/gitignore.nvim"
rev = "47cefc0b6ea412e1e149552b10ebfe9f7f0b8952"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v1.0.2"
#
[plugins.ne]
git = "neogitorg/neogit"
rev = "v2.0.0"
#
#
[plugins."linediff.vim"]
git = "andrewradev/linediff.vim"
rev = "v0.3.0"

[plugins."octo.nvim"]
git = "pwntester/octo.nvim"
rev = "dc2721ca48c9c08bdbb94586fece9e2c7b21ce4d"
opt = true

[plugins."smartyank.nvim"]
git = "ibhagwan/smartyank.nvim"
rev = "0a4554a4ea4cad73dab0a15e559f2128ca03c7b2"

[plugins."cool-substitute.nvim"]
git = "otavioschwanck/cool-substitute.nvim"
rev = "2095e2304aecfea4b6c2a8b1a9e1794b5920472c"
opt = true

[plugins."text-case.nvim"]
git = "johmsalas/text-case.nvim"
rev = "v1.2.0"

[plugins.vim-camelsnek]
git = "nicwest/vim-camelsnek"
rev = "84b363aa42b5bc3a2314a56d242df20e7bbfcbf3"

[plugins.undotree]
git = "mbbill/undotree"
rev = "b951b87b46c34356d44aa71886aecf9dd7f5788a"

[plugins."img-clip.nvim"]
git = "hakonharnes/img-clip.nvim"
rev = "v0.6.0"

[plugins."nvim-neoclip.lua"]
git = "acksld/nvim-neoclip.lua"
rev = "831a97c7697736411a05ff8b91e8798ea4c2d6fb"

[plugins."yanki.nvim"]
git = "romanozumbe/yanki.nvim"
rev = "ebccf6ec45c30a70a9a80bb93d2619584f2c6b8d"

[plugins.vim-maximizer]
git = "szw/vim-maximizer"
rev = "2e54952fe91e140a2e69f35f22131219fcd9c5f1"

[plugins."winshift.nvim"]
git = "sindrets/winshift.nvim"
rev = "37468ed6f385dfb50402368669766504c0e15583"

[plugins."kitty-scrollback.nvim"]
git = "mikesmithgh/kitty-scrollback.nvim"
rev = "v6.3.0"

[plugins."expand.nvim"]
git = "sam-programs/expand.nvim"
rev = "c8fb5726e8ca747e709966737566fb628cb95894"
opt = true

[plugins."scrollofffraction.nvim"]
git = "nkakouros-original/scrollofffraction.nvim"
rev = "0618a3e3e1a4e13a04edf6fd35bfcee4bd5afe38"

[plugins."open-handlers.nvim"]
git = "mrshmllow/open-handlers.nvim"
rev = "62e8a7abeb8b5eb374dfa4be396c97f5f44e7323"

[plugins."bmessages.nvim"]
git = "ariel-frischer/bmessages.nvim"
rev = "985c6973bc27888598a03f4766a2481248a599b2"

[plugins."modes.nvim"]
git = "mvllow/modes.nvim"
rev = "v0.2.1"

[plugins."gx.nvim"]
git = "chrishrb/gx.nvim"
rev = "v0.7.0"
#
[plugins."easypick.nvim"]
git = "axkirillov/easypick.nvim"
rev = "v0.6.0"
opt = true

[plugins."telescope-file-browser.nvim"]
git = "nvim-telescope/telescope-file-browser.nvim"
rev = "626998e5c1b71c130d8bc6cf7abb6709b98287bb"

[plugins.telescope-sg]
git = "marskey/telescope-sg"
rev = "caceaa670f26a581fb20ce99576ed8155c3ae96d"

[plugins."telescope-live-grep-args.nvim"]
git = "nvim-telescope/telescope-live-grep-args.nvim"
rev = "v1.1.0"

[plugins.telescope-zoxide]
git = "jvgrootveld/telescope-zoxide"
rev = "v2.1"

[plugins."smart-open.nvim"]
git = "danielfalk/smart-open.nvim"
rev = "7770b01ce4d551c143d7ec8589879320796621b9"
opt = true

[plugins."hlargs.nvim"]
git = "m-demare/hlargs.nvim"
rev = "063fa2ba05f5eee5a1ab3da76ecb19770b7725cf"

[plugins.hipairs]
git = "yggdroot/hipairs"
rev = "8272bf6979d0ee65a3fdbbb97eff3dda79b661b2"

[plugins.ts-node-action]
git = "ckolkey/ts-node-action"
rev = "bfaa787cc85d753af3c19245b4142ed727a534b5"

[plugins."equal.operator"]
git = "romgrk/equal.operator"
rev = "5c4cb737db8ded6bf56bbf090fda2b81efa7028c"

[plugins.vim-kitty]
git = "fladson/vim-kitty"
rev = "v1.2"

[plugins."diaglist.nvim"]
git = "onsails/diaglist.nvim"
rev = "afc124a0976d56db43cc840e62757193ccab7856"

[plugins.vim-dirtytalk]
git = "psliwka/vim-dirtytalk"
rev = "aa57ba902b04341a04ff97214360f56856493583"

[plugins."stay-in-place.nvim"]
git = "gbprod/stay-in-place.nvim"
rev = "v1.0.0"

[plugins."carbon-now.nvim"]
git = "ellisonleao/carbon-now.nvim"
rev = "0.2.0"

[plugins."hypersonic.nvim"]
git = "tomiis4/hypersonic.nvim"
rev = "734dfbfbe51952f102a9b439d53d4267bb0024cd"

[plugins."maim.nvim"]
git = "kiran94/maim.nvim"
rev = "v1.0.1"

[plugins."dmacro.nvim"]
git = "tani/dmacro.nvim"
rev = "25ab1df31d216c4ff7554c262f92b5c0c6b743f0"

[plugins."fold-cycle.nvim"]
git = "jghauser/fold-cycle.nvim"
rev = "20e9b468b771ebf33b6806a0e872eee53c5a20c9"

[plugins."scope.nvim"]
git = "tiagovla/scope.nvim"
rev = "3fc963e75f88990a9467ff72b8eea667a69c30a2"

[plugins."reach.nvim"]
git = "toppair/reach.nvim"
rev = "f86830357941cca8a31f19601153087ea9524d22"

[plugins.bufexplorer]
git = "jlanzarotta/bufexplorer"
rev = "7.11.0"
opt = true

[plugins."bufonly.nvim"]
git = "numtostr/bufonly.nvim"
rev = "30579c2851743b00c4547c324a16f2c1cfa5a41c"

[plugins."stickybuf.nvim"]
git = "stevearc/stickybuf.nvim"
rev = "v2.0.0"

[plugins."local-yokel.nvim"]
git = "mskelton/local-yokel.nvim"
rev = "d522a14952ac959f6b948fbf156c4ded34f90f12"
opt = true

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.9.1"

[plugins.nvim-hlslens]
git = "kevinhwang91/nvim-hlslens"
rev = "v1.1.0"

[plugins."which-key.nvim"]
git = "dimeji-go/which-key.nvim"
rev = "500806761020be505228c1d010f4c29c6c0824ac"

[plugins.vim-eunuch]
git = "tpope/vim-eunuch"
rev = "v1.3"

[plugins.harpoon]
git = "theprimeagen/harpoon"
rev = "harpoon2"

[plugins."yeet.nvim"]
git = "samharju/yeet.nvim"
rev = "v1.3.0"

[plugins.vim-repeat]
git = "tpope/vim-repeat"
rev = "v1.2"

[plugins.vim-illuminate]
git = "rrethy/vim-illuminate"
rev = "19cb21f513fc2b02f0c66be70107741e837516a1"
opt = true

[plugins."lasterisk.nvim"]
git = "rapan931/lasterisk.nvim"
rev = "bbcfcaeca50f686e338a03386e41645fc3305f44"

[plugins.vim-edgemotion]
git = "haya14busa/vim-edgemotion"
rev = "8d16bd92f6203dfe44157d43be7880f34fd5c060"

[plugins."accelerated-jk.nvim"]
git = "rainbowhxch/accelerated-jk.nvim"
rev = "8fb5dad4ccc1811766cebf16b544038aeeb7806f"

[plugins.vim-exchange]
git = "tommcdo/vim-exchange"
rev = "d6c1e9790bcb8df27c483a37167459bbebe0112e"

[plugins.overseer-quick-tasks]
git = "itsfrank/overseer-quick-tasks"
rev = "b5f03c4feab7a7a8008c3b651042586c9f3c5b71"

[plugins."sibling-swap.nvim"]
git = "wansmer/sibling-swap.nvim"
rev = "4d3b8a9d80a8b3c8d76e74c2bdd13b6e7c4f8258"

[plugins.vim-smartq]
git = "marklcrns/vim-smartq"
rev = "v1.4.1"

[plugins."telescope-bookmarks.nvim"]
git = "dhruvmanila/telescope-bookmarks.nvim"
rev = "v4.0.0"

[plugins."zoxide.vim"]
git = "nanotee/zoxide.vim"
rev = "b1e70b6fc1682a83929aee63680d2b43456fe9a5"

[plugins."grug-far.nvim"]
git = "magicduck/grug-far.nvim"
rev = "1.6.0"

[plugins."ssr.nvim"]
git = "cshuaimin/ssr.nvim"
rev = "7c95cfa5836508f08ae833a4b31d2ed265560f64"

[plugins."muren.nvim"]
git = "acksld/muren.nvim"
rev = "fa18f2df80a52afd201da062d1af0e80c8d1988e"

[plugins.nvim-dd]
git = "yorickpeterse/nvim-dd"
rev = "ebd9398271d3249fe97ffb52365fb6ace7605277"

[plugins."troublesum.nvim"]
git = "ivanjermakov/troublesum.nvim"
rev = "b00301bb565bfcb6fcfa41f2012e43a0528da65b"

[plugins.better-diagnostic-virtual-text]
git = "sontungexpt/better-diagnostic-virtual-text"
rev = "eb3a77e714aa6c295bdb4f074fccbda637090f6e"

[plugins."mason-null-ls.nvim"]
git = "jay-babu/mason-null-ls.nvim"
rev = "v2.6.0"
opt = true

[plugins."none-ls-autoload.nvim"]
git = "zeioth/none-ls-autoload.nvim"
rev = "v1.0.0"
opt = true

[plugins."luasnip-latex-snippets.nvim"]
git = "iurimateus/luasnip-latex-snippets.nvim"
rev = "498f4ba12d025487939d89b801647b44bb15676c"

[plugins.neorg-hop-extras]
git = "phenax/neorg-hop-extras"
rev = "f349ab3e9a52d214f1af6122cd087218b2722c81"

[plugins.neorg-exec]
git = "laher/neorg-exec"
rev = "90064eaeee596eb6ec1c476cf26ea0087861faed"

[plugins."refactoring.nvim"]
git = "theprimeagen/refactoring.nvim"
rev = "36bd14ddd7ebf0546c15e6088e8bc93f8a98787d"
opt = true

[plugins."python-copy-reference.vim"]
git = "ranelpadon/python-copy-reference.vim"
rev = "8172d0ce83d730820d9497fd2e988046022d0b99"
opt = true

[plugins."direnv.vim"]
git = "direnv/direnv.vim"
rev = "ab2a7e08dd630060cd81d7946739ac7442a4f269"
opt = true

[plugins."oil-image-preview.nvim"]
git = "mimikun/oil-image-preview.nvim"
rev = "f1da1c2925026d1a0b6618209af24ab4e03ebe8b"
opt = true

[plugins.abstract-autocmds]
git = "abstract-ide/abstract-autocmds"
rev = "d2e4cfd67cf59166f9ffa0bd3bc90899ffc653e7"

[plugins."fileline.nvim"]
git = "lewis6991/fileline.nvim"
rev = "c116aa8dd7aa7e1db6938f872285e598dc9ee00b"

[plugins."hlchunk.nvim"]
version = "1.3.0"
opt = true

[plugins."definition-or-references.nvim"]
git = "kostkabrukowa/definition-or-references.nvim"
rev = "13570f995be8993f4c55e988f89e5a7b8df37a17"

[plugins."diagnostic-window.nvim"]
git = "cseickel/diagnostic-window.nvim"
rev = "2b4d9618382502740c7945c4023853ee524adc4c"
opt = true

[plugins."copilot.lua"]
git = "zbirenbaum/copilot.lua"
rev = "b8fc1a573013ce461b4d4deedea5636e8517ac72"
opt = true

[plugins."kanagawa-paper.nvim"]
git = "sho-87/kanagawa-paper.nvim"
rev = "v2.0.1"

[plugins."none-ls.nvim"]
version = "scm"
opt = true

[plugins."glance.nvim"]
version = "scm"
opt = true

[plugins."exemplum.nvim"]
git = "ntbbloodbath/exemplum.nvim"
rev = "6c2efa83d2f1009ca86f7182e0ea07dfa7646518"
opt = true

[plugins.nvim-rip-substitute]
git = "chrisgrieser/nvim-rip-substitute"
rev = "2b659699afce3efccac7a23467641f17ce042807"
opt = true
#
[plugins."guihua.lua"]
git = "ray-x/guihua.lua"
rev = "v0.1"

[plugins."multicursors.nvim"]
git = "smoka7/multicursors.nvim"
rev = "v2.0.0"
opt = true

[plugins."hydra.nvim"]
git = "cathyprime/hydra.nvim"
rev = "0809bdf09583631232dbca34fe92116053bb2d1f"
opt = true

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v1.1.1"

[plugins."blink.compat"]
git = "saghen/blink.compat"
rev = "v2.5.0"

[plugins.vim-matchup]
git = "andymass/vim-matchup"
rev = "v0.7.3"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.3"
#
[bundles.startup]
items = [
  "abstract-autocmds",
]
#
#
[bundles.completion] # Create a bundle called `lsp`
items = [
  "blink.cmp",
  "luasnip",
  "friendly-snippets",
  "luasnip-snippets",
  "luasnip-latex-snippets.nvim",
  "nvim-autopairs",
  "neotab.nvim",
  "mason-lspconfig.nvim",
  "mason.nvim",

]
# #
[bundles.lsp]
items = [
  "nvim-lspconfig",
  "lsp-command",
  "avante.nvim"

]
#
[bundles.ui]
items = [
  "dropbar.nvim",
]


[bundles.test]
items = [
  "nvim-surround",
  "nvim-spider",
  "oil.nvim",
  "dmacro.nvim",
]

[bundles.search]
items = [
"telescope.nvim"
]
#
[config]
auto_setup = true
colorscheme = "kanagawa-paper"

[rocks_lazy]
import = "lazy_specs"
