# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "scm"
"rocks-config.nvim" = "scm"
"rocks-git.nvim" = "scm"
"rocks-lazy.nvim" = "scm"

# tree-sitter parsers
tree-sitter-zig = "scm"
tree-sitter-lua = "scm"
tree-sitter-luadoc = "scm"
tree-sitter-json = "scm"
tree-sitter-toml = "scm"
tree-sitter-fish = "scm"
tree-sitter-html = "scm"
tree-sitter-css = "scm"
tree-sitter-jsdoc = "scm"
tree-sitter-javascript = "scm"
tree-sitter-typescript = "scm"
tree-sitter-vim = "scm"
tree-sitter-elixir = "scm"
tree-sitter-rust = "scm"
tree-sitter-comment = "scm"
tree-sitter-python = "scm"
nvim-notify = "3.13.5"

[plugins."lspkind.nvim" ]
git = "onsails/lspkind.nvim"


[plugins.luasnip]
git = "l3mon4d3/luasnip"
rev = "v2.3.0"

[plugins.nvim-cmp]
event = "InsertEnter"
version = "0.0.1"

[plugins.cmp-async-path]
git = "felipelema/cmp-async-path"
rev = "main"

[plugins.cmp-path]
git = "hrsh7th/cmp-path"
rev = "main"

[plugins.cmp-omni]
git = "hrsh7th/cmp-omni"
rev = "main"

[plugins.cmp-cmdline]
git = "hrsh7th/cmp-cmdline"
rev = "main"

[plugins.cmp-git]
git = "petertriho/cmp-git"
rev = "main"

[plugins.cmp-luasnip]
git = "saadparwaiz1/cmp_luasnip"
rev = "main"

[plugins.cmp-spell]
git = "f3fora/cmp-spell"
rev = "main"

[plugins.cmp-vimtex]
git = "micangl/cmp-vimtex"
rev = "main"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"
rev = "main"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"
rev = "main"

[plugins.luasnip-snippets]
git = "mireq/luasnip-snippets"
rev = "main"

[plugins.luasnip-latex-snippets]
git = "iurimateus/luasnip-latex-snippets.nvim"
rev = "main"

[plugins.ultimate-autopair]
git = "altermo/ultimate-autopair.nvim"
rev = "main"

[plugins.nvim-autopairs]
git = "windwp/nvim-autopairs"
rev = "main"

[plugins.nvim-scissors]
git = "chrisgrieser/nvim-scissors"
rev = "main"

[plugins.vim-dadbod-completion]
git = "kristijanhusak/vim-dadbod-completion"
rev = "main"

[plugins.vim-sonictemplate]
git = "vsedov/vim-sonictemplate"
rev = "main"

[plugins."kanagawa.nvim"]
rev = "master"
colorscheme = [
  "kanagawa",
  "kanagawa-dragon",
  "kanagawa-lotus",
  "kanagawa-wave"
]

[plugins.snippetgenie]
git = "ziontee113/snippetgenie"

[plugins."neotab.nvim"]
git = "kawre/neotab.nvim"

[plugins."garbage-day.nvim"]
git = "zeioth/garbage-day.nvim"
rev = "v1.3.0"
opts = true

[plugins.better-diagnostic-virtual-text]
git = "sontungexpt/better-diagnostic-virtual-text"

[plugins."diagflow.nvim"]
git = "dgagn/diagflow.nvim"

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
rev = "v3.0.0^{}"

[plugins."troublesum.nvim"]
git = "ivanjermakov/troublesum.nvim"

[plugins.lsp_extra_dim]
git = "askfiy/lsp_extra_dim"

[plugins.nvim-dd]
git = "yorickpeterse/nvim-dd"

[plugins."definition-or-references.nvim"]
git = "kostkabrukowa/definition-or-references.nvim"

[plugins."glance.nvim"]
git = "dnlhc/glance.nvim"

[plugins."nui.nvim"]
git = "muniftanjim/nui.nvim"
rev = "0.3.0"

[plugins."diagnostic-window.nvim"]
git = "cseickel/diagnostic-window.nvim"

[plugins."inc-rename.nvim"]
git = "smjonas/inc-rename.nvim"

[plugins."lsp-format-modifications.nvim"]
git = "joechrisellis/lsp-format-modifications.nvim"

[plugins."actions-preview.nvim"]
git = "aznhe21/actions-preview.nvim"

[plugins."lsp_signature.nvim"]
git = "ray-x/lsp_signature.nvim"
rev = "v0.3.1"

[plugins."lspsaga.nvim"]
git = "glepnir/lspsaga.nvim"

[plugins."hover.nvim"]
git = "lewis6991/hover.nvim"
opt = true

[plugins."clangd_extensions.nvim"]
git = "p00f/clangd_extensions.nvim"

[plugins.lsp-command]
git = "ii14/lsp-command"

[plugins."mason-null-ls.nvim"]
git = "jayp0521/mason-null-ls.nvim"
rev = "v2.6.0"

[plugins."typos.nvim"]
git = "poljar/typos.nvim"

[plugins."plenary.nvim"]
git = "nvim-lua/plenary.nvim"
rev = "v0.1.4"

[plugins."none-ls.nvim"]
git = "nvimtools/none-ls.nvim"

[plugins."neoconf.nvim"]
git = "folke/neoconf.nvim"
rev = "v1.3.2"

[plugins."neodev.nvim"]
git = "folke/neodev.nvim"
rev = "v3.0.0"

[plugins."mason-lspconfig.nvim"]
git = "williamboman/mason-lspconfig.nvim"
rev = "v1.9.0"

[plugins."mason.nvim"]
git = "williamboman/mason.nvim"
rev = "v1.9.0"

[plugins.nvim-lspconfig]
git = "neovim/nvim-lspconfig"
rev = "v0.1.8"


[bundles.completion] # Create a bundle called `lsp`
items = [
    "nvim-cmp",
    "luasnip",
    "cmp-async-path",
    "cmp-path",
    "cmp-omni",
    "cmp-cmdline",
    "cmp-git",
    "cmp-luasnip",
    "cmp-spell",
    "cmp-vimtex",
    "cmp-buffer",
    "friendly-snippets",
    "luasnip-snippets",
    "luasnip-latex-snippets",
    "ultimate-autopair",
    "nvim-autopairs",
    "nvim-scissors",
    "vim-dadbod-completion",
    "vim-sonictemplate",
]
[bundles.lsp]
items = [ 

]

[config]
auto_setup = true
colorscheme = "kanagawa"

# rocks-treesitter
[treesitter]
auto_highlight = "all"
auto_install = "prompt"


