
[treesitter]
auto_highlight = "all"
auto_install = "prompt"
# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!

[plugins]
"rocks.nvim" = "2.40.2"
"rocks-config.nvim" = "3.0.0"
"heirline.nvim" = "scm"
"nvim-spider" = "scm"
"rocks-lazy.nvim" = "scm"
"lspkind.nvim" = "scm"
nvim-notify = "scm"
friendly-snippets = "scm"
nvim-lspconfig = "1.0.0"
"mason-lspconfig.nvim" = "scm"
"mason.nvim" = "scm"
"better-escape.nvim" = {version= "scm", opt = true}
"actions-preview.nvim" = {version= "scm", opt = true}
"inc-rename.nvim" = {version= "scm", opt = true}
treesj = {version= "scm", opt = true}
"dial.nvim" = {version= "scm", opt = true}
"comment-box.nvim" = "scm"
"comment.nvim" = {version= "scm", opt = true}
"flash.nvim" = {version= "scm", opt = true}
"mini.visits" = "scm"
"dropbar.nvim" = "8.6.1"
"fidget.nvim" = "1.4.1"
"indent-blankline.nvim" = "scm"
nvim-web-devicons = "0.100"
"nui.nvim" = "dev"
"oil.nvim" = "scm"
"bufdelete.nvim" = "scm"
nvim-nio = "1.10.0"
"image.nvim" = "1.3.0"
"rocks-dev.nvim" = "1.7.0"
"glow.nvim" = "0.2.0"
toml = "0.4.0"
luv = "1.48.0"
luasnip = "2.3.0"
"plenary.nvim" = "scm"
lzn-auto-require = "0.1.0"
nvim-autopairs = "scm"
nvim-surround = "2.1.5"
"rainbow-delimiters.nvim" = "scm"
"toggleterm.nvim" = "scm"
"yanky.nvim" = "scm"
"telescope-zf-native.nvim" = "1.0.0"
cmp_luasnip = {version= "scm" }
"substitute.nvim" = "scm"
nvim-various-textobjs = "scm"
"guess-indent.nvim" = "scm"
"smart-splits.nvim" = "scm"
"dressing.nvim" = "scm"
"none-ls-extras.nvim" = "scm"
"logging.nvim" = "1.1.0"
nvim-ufo = "1.4.0"
"yazi.nvim" = "6.2.0"
"telescope.nvim" = "scm"
"sqlite.lua" = "scm"
nvim-dap = "scm"
"iswap.nvim" = "scm"
"overseer.nvim" = "scm"
tree-sitter-python = "scm"
"navigator.lua" = "scm"
tree-sitter-toml = "scm"
tree-sitter-lua = "scm"
"rocks-git.nvim" = "2.3.1"
nvim-treesitter-legacy-api = "scm"
"rocks-treesitter.nvim" = "scm"
tree-sitter-latex = "scm"
nvim-cmp = {version= "scm", opt=false}
neorg-se = "1.1.10"
"trouble.nvim" = "3.6.0"

[plugins.neorg-interim-ls ]
version = "1.2.1"
opt = true

[plugins.neorg ]
version = "9.1.1"
opt = true


# will need to reload this manually because i do not get this not working
[plugins."sg.nvim"]
version = "scm"

[plugins."render-markdown.nvim"]
version = "7.1.0"
opt = true

[plugins.promise-async ]
version = "scm"
opt = true

[plugins."cybu.nvim" ]
git = "ghillb/cybu.nvim"
rev = "v1.0^{}"
opt = true

[plugins.nvim-window-picker ]
version = "2.0.3"


[plugins.cmp-path]
git = "hrsh7th/cmp-path"
rev = "91ff86cd9c29299a64f968ebb45846c485725f23"

[plugins.cmp-nvim-lsp ]
git = "hrsh7th/cmp-nvim-lsp"
rev = "main"
opt = false


[plugins.cmp-vimtex]
git = "micangl/cmp-vimtex"
rev = "5283bf9108ef33d41e704027b9ef22437ce7a15b"



[plugins."neotab.nvim"]
git = "kawre/neotab.nvim"
rev = "6c6107dddaa051504e433608f59eca606138269b"


[plugins."garbage-day.nvim"]
git = "zeioth/garbage-day.nvim"
rev = "v1.3.0"
opt = true

[plugins.lsp-command]
git = "ii14/lsp-command"
rev = "b2d130d0358f7d64cd967c918182bce25944737b"

[plugins.luasnip-snippets]
git = "mireq/luasnip-snippets"
rev = "0.1.2"

[plugins."cmdline.nvim"]
git = "vzze/cmdline.nvim"
rev = "b7af6a91c0762f2a823d6e79912d8b99e014b6fd"

[plugins."bufex.nvim"]
git = "tomiis4/bufex.nvim"
rev = "b7a3f8d610f383f3b28ffb6e7ebdb6bd1deb56e3"

[plugins.nvim-conda]
git = "kmontocam/nvim-conda"
rev = "v0.2.1"

[plugins."requirements.txt.vim"]
git = "raimon49/requirements.txt.vim"
rev = "v-1.9.0^{}"

[plugins.neorg-templates-draft]
git = "pysan3/neorg-templates-draft"
rev = "v2.0.3"

[plugins.neorg-telescope]
git = "nvim-neorg/neorg-telescope"
rev = "v1.2.3"

[plugins."arrow.nvim"]
git = "otavioschwanck/arrow.nvim"
rev = "fb8e2cf548f625f6e36cb44d3e65600656924234"
opt = true

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.9"

[plugins.vim-rooter]
git = "airblade/vim-rooter"
rev = "4a0df2f1b0f3d69e8f7e19afe464a7c3a7af89a2"

[plugins."nui-components.nvim"]
git = "grapp-dev/nui-components.nvim"
rev = "v1.5.2"

[plugins."refgo.nvim"]
git = "prichrd/refgo.nvim"
rev = "5e8b4ef4536998d7611010e6dc7fbab131bc22ad"

[plugins.nvim-docs-view]
git = "amrbashir/nvim-docs-view"
rev = "365593534e0acd762bfddce6e8313315ffa4fa36"
opt = true

[plugins.vim-devdocs]
git = "romainl/vim-devdocs"
rev = "85a98b86043ac6b4484663d75729e1b5bcebedbe"

[plugins."browse.nvim"]
git = "lalitmee/browse.nvim"
rev = "8292baa12ef4611532526e8a6f7a315848eceb74"

[plugins."wtf.nvim"]
git = "piersolenski/wtf.nvim"
rev = "d75acc087b5183b0b3e000189518c5d799978e95"

[plugins."compiler-explorer.nvim"]
git = "krady21/compiler-explorer.nvim"
rev = "ee8e7a2808bdad67cd2acb61b5c9ffa7735c7ec9"

[plugins.nvim-coverage]
git = "andythigpen/nvim-coverage"
rev = "aa4b4400588e2259e87e372b1e4e90ae13cf5a39"

[plugins."officer.nvim"]
git = "pianocomposer321/officer.nvim"
rev = "60b046e1068081d965f36fa8d728d6f2bc41ab77"

[plugins."compiler.nvim"]
git = "zeioth/compiler.nvim"
rev = "v3.3.8"
opt = true

[plugins."chatgpt.nvim"]
git = "jackmort/chatgpt.nvim"
rev = "v0.1.1-alpha"

[plugins."quicker.nvim"]
git = "stevearc/quicker.nvim"
rev = "v1.1.1"

[plugins."watch.nvim"]
git = "makaze/watch.nvim"
rev = "v0.4.1"

[plugins.vim-grammarous]
git = "rhysd/vim-grammarous"
rev = "db46357465ce587d5325e816235b5e92415f8c05"

[plugins.vim-markdown]
git = "plasticboy/vim-markdown"
rev = "2.0.0"

[plugins."markdown-preview.nvim"]
git = "iamcco/markdown-preview.nvim"
rev = "v0.0.9^{}"

[plugins.vim-translator]
git = "voldikss/vim-translator"
rev = "6f0639c6d471a3a90ac19db96e1e379c030f74e3"

[plugins."pre-commit.nvim"]
git = "ttibsi/pre-commit.nvim"
rev = "v1.0.0^{}"

[plugins."suda.vim"]
git = "lambdalisue/suda.vim"
rev = "v1.2.2"

[plugins."capslock.nvim"]
git = "barklan/capslock.nvim"
rev = "v1.4.1^{}"

[plugins.vim-startuptime]
git = "dstein64/vim-startuptime"
rev = "v4.5.0"

[plugins.nvim-genghis]
git = "chrisgrieser/nvim-genghis"
rev = "382ddb90a31313f0b2e059db50df0ca4dd2859d2"

[plugins.nvim-fundo]
git = "kevinhwang91/nvim-fundo"
rev = "ac9c9372c4bf677721e24f144ef29d3a05c2b589"
opt = true


[plugins."term-edit.nvim"]
git = "chomosuke/term-edit.nvim"
event = "TermEnter"
rev = "v1.3.1"

[plugins.nvim-jqx]
git = "gennaro-tedesco/nvim-jqx"
rev = "v0.1.4^{}"

[plugins."gist.nvim"]
git = "rawnly/gist.nvim"
rev = "0.0.6"

[plugins."gitignore.nvim"]
git = "wintermute-cell/gitignore.nvim"
rev = "2455191ec94da8ed222806a4fe3aa358eac1e558"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins.ne]
git = "neogitorg/neogit"
rev = "v1.0.0"

[plugins."co-author.nvim"]
git = "2kabhishek/co-author.nvim"
rev = "db0debbde453c0ce10d1b925cd9f3139e4291c42"

[plugins."linediff.vim"]
git = "andrewradev/linediff.vim"
rev = "v0.3.0"

[plugins."octo.nvim"]
git = "pwntester/octo.nvim"
rev = "0134169886958f3874f16eed7fe73d906a3e7e17"
opt =true

[plugins."smartyank.nvim"]
git = "ibhagwan/smartyank.nvim"
rev = "d9e078fe08d6466e37ea45ac446a9f60e6866789"

[plugins."cool-substitute.nvim"]
git = "otavioschwanck/cool-substitute.nvim"
rev = "2095e2304aecfea4b6c2a8b1a9e1794b5920472c"
opt = true

[plugins."text-case.nvim"]
git = "johmsalas/text-case.nvim"
rev = "v1.2.0"

[plugins.vim-camelsnek]
git = "nicwest/vim-camelsnek"
rev = "84b363aa42b5bc3a2314a56d242df20e7bbfcbf3"

[plugins.undotree]
git = "mbbill/undotree"
rev = "rel_6.1"

[plugins."img-clip.nvim"]
git = "hakonharnes/img-clip.nvim"
rev = "v0.5.0"

[plugins."nvim-neoclip.lua"]
git = "acksld/nvim-neoclip.lua"
rev = "709c97fabec9da7d04f7d2f5e207423af8c02871"

[plugins."yanki.nvim"]
git = "romanozumbe/yanki.nvim"
rev = "ebccf6ec45c30a70a9a80bb93d2619584f2c6b8d"

[plugins.vim-maximizer]
git = "szw/vim-maximizer"
rev = "2e54952fe91e140a2e69f35f22131219fcd9c5f1"

[plugins."winshift.nvim"]
git = "sindrets/winshift.nvim"
rev = "37468ed6f385dfb50402368669766504c0e15583"

[plugins."bufresize.nvim"]
git = "kwkarlwang/bufresize.nvim"
rev = "3b19527ab936d6910484dcc20fb59bdb12322d8b"

[plugins."indent.nvim"]
git = "sam-programs/indent.nvim"
rev = "883c7f32f349c1ff1a47167c553c237a914ea6f4"

[plugins."urlview.nvim"]
git = "axieax/urlview.nvim"
rev = "v0.6-compat"

[plugins."kitty-scrollback.nvim"]
git = "mikesmithgh/kitty-scrollback.nvim"
rev = "v5.0.1"

[plugins."expand.nvim"]
git = "sam-programs/expand.nvim"
rev = "c8fb5726e8ca747e709966737566fb628cb95894"
opt = true

[plugins."scrollofffraction.nvim"]
git = "nkakouros-original/scrollofffraction.nvim"
rev = "0618a3e3e1a4e13a04edf6fd35bfcee4bd5afe38"

[plugins."nvim-rgflow.lua"]
git = "mangelozzi/nvim-rgflow.lua"
rev = "8a2d80b8594591163d06b430be18c7376d5ae1b8"

[plugins."open-handlers.nvim"]
git = "mrshmllow/open-handlers.nvim"
rev = "62e8a7abeb8b5eb374dfa4be396c97f5f44e7323"

[plugins."bmessages.nvim"]
git = "ariel-frischer/bmessages.nvim"
rev = "cad159ee584932d1a631ca7c5a2e6e58d3e9981e"

[plugins."nerdy.nvim"]
git = "2kabhishek/nerdy.nvim"
rev = "1.2"

[plugins."portal.nvim"]
git = "cbochs/portal.nvim"
rev = "v0.9.0"

[plugins."calculator.nvim"]
git = "vzze/calculator.nvim"
rev = "1e417c69606318575082ffc283b501523c2ba4ab"

[plugins."neominimap.nvim"]
git = "isrothy/neominimap.nvim"
rev = "v3.7.2"
opt = true

[plugins."moody.nvim"]
git = "svampkorg/moody.nvim"
rev = "189bd6e9bc858e1608d7b29839f6f4134d772bf3"

[plugins."modes.nvim"]
git = "mvllow/modes.nvim"
rev = "v0.2.1"

[plugins."hunk.nvim"]
git = "julienvincent/hunk.nvim"
rev = "v1.5.0"

[plugins."toggle-overlength.nvim"]
git = "fouladi/toggle-overlength.nvim"
rev = "00a8b5c17b8dcbafd13fcef39c2120c923c069b7"

[plugins."gx.nvim"]
git = "chrishrb/gx.nvim"
rev = "v0.7.0"

[plugins."easypick.nvim"]
git = "axkirillov/easypick.nvim"
rev = "v0.6.0"
opt = true

[plugins."telescope-file-browser.nvim"]
git = "nvim-telescope/telescope-file-browser.nvim"
rev = "a46780830b576049c675680650f773bedfa8677a"

[plugins."telescope-frecency.nvim"]
git = "nvim-telescope/telescope-frecency.nvim"
rev = "38f2a2207e475916a7532bfd9f9c5d7353a1ce7b"

[plugins.telescope-sg]
git = "marskey/telescope-sg"
rev = "caceaa670f26a581fb20ce99576ed8155c3ae96d"

[plugins."telescope-live-grep-args.nvim"]
git = "nvim-telescope/telescope-live-grep-args.nvim"
rev = "v1.1.0^{}"

[plugins.telescope-zoxide]
git = "jvgrootveld/telescope-zoxide"
rev = "v2.1"

[plugins."smart-open.nvim"]
git = "danielfalk/smart-open.nvim"
rev = "f4e39e9a1b05a6b82b1182a013677acc44b27abb"
opt = true


[plugins."hlargs.nvim"]
git = "m-demare/hlargs.nvim"
rev = "cc0d9ee75e5ffba730393049119361b9e3a5b1b6"

[plugins.hipairs]
git = "yggdroot/hipairs"
rev = "8272bf6979d0ee65a3fdbbb97eff3dda79b661b2"

[plugins.ts-node-action]
git = "ckolkey/ts-node-action"
rev = "6d3b60754fd87963d70eadaa2f77873b447eac26"

[plugins."equal.operator"]
git = "romgrk/equal.operator"
rev = "5c4cb737db8ded6bf56bbf090fda2b81efa7028c"

[plugins.vim-kitty]
git = "fladson/vim-kitty"
rev = "9cc594a634308aa3bfaf3da5b5e741da1c0144c1"

[plugins."diaglist.nvim"]
git = "onsails/diaglist.nvim"
rev = "afc124a0976d56db43cc840e62757193ccab7856"

[plugins.vim-dirtytalk]
git = "psliwka/vim-dirtytalk"
rev = "aa57ba902b04341a04ff97214360f56856493583"

[plugins."stay-in-place.nvim"]
git = "gbprod/stay-in-place.nvim"
rev = "v1.0.0"

[plugins."carbon-now.nvim"]
git = "ellisonleao/carbon-now.nvim"
rev = "0.2.0^{}"

[plugins."hypersonic.nvim"]
git = "tomiis4/hypersonic.nvim"
rev = "734dfbfbe51952f102a9b439d53d4267bb0024cd"

[plugins."maim.nvim"]
git = "kiran94/maim.nvim"
rev = "v1.0.1"

[plugins."dmacro.nvim"]
git = "tani/dmacro.nvim"
rev = "95eaf53bc7a4b3dead220fe1f28870b60524a215"

[plugins."fold-cycle.nvim"]
git = "jghauser/fold-cycle.nvim"
rev = "20e9b468b771ebf33b6806a0e872eee53c5a20c9"

[plugins."scope.nvim"]
git = "tiagovla/scope.nvim"
rev = "5e3f5ead970317b2f276d38dc031cb4bc5742cd4"

[plugins."reach.nvim"]
git = "toppair/reach.nvim"
rev = "f86830357941cca8a31f19601153087ea9524d22"

[plugins.bufexplorer]
git = "jlanzarotta/bufexplorer"
rev = "v7.4.9"
opt = true

[plugins."bufonly.nvim"]
git = "numtostr/bufonly.nvim"
rev = "30579c2851743b00c4547c324a16f2c1cfa5a41c"

[plugins."stickybuf.nvim"]
git = "stevearc/stickybuf.nvim"
rev = "v2.0.0"

[plugins."local-yokel.nvim"]
git = "mskelton/local-yokel.nvim"
rev = "d522a14952ac959f6b948fbf156c4ded34f90f12"
opt = true

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.9.1^{}"

[plugins.nvim-hlslens]
git = "kevinhwang91/nvim-hlslens"
rev = "v1.0.0"

[plugins."which-key.nvim"]
git = "dimeji-go/which-key.nvim"
rev = "500806761020be505228c1d010f4c29c6c0824ac"

# [plugins."neo-tree-jj.nvim"]
# git = "cretezy/neo-tree-jj.nvim"
# rev = "c6534930c6f79893e12eafbb722ee23e6a83e80e"

[plugins.vim-eunuch]
git = "tpope/vim-eunuch"
rev = "v1.3^{}"

[plugins.harpoon]
git = "stroiman/harpoon"
rev = "f9a2ff215379fadf1e1e4f781ca2dc31413f1f40"
branch = "harpoon2"

[plugins."yeet.nvim"]
git = "samharju/yeet.nvim"
rev = "v1.2.1"

[plugins.vim-repeat]
git = "tpope/vim-repeat"
rev = "v1.2^{}"

[plugins.vim-illuminate]
git = "rrethy/vim-illuminate"
rev = "5eeb7951fc630682c322e88a9bbdae5c224ff0aa"
opt = true

[plugins."lasterisk.nvim"]
git = "rapan931/lasterisk.nvim"
rev = "bbcfcaeca50f686e338a03386e41645fc3305f44"

[plugins.vim-edgemotion]
git = "haya14busa/vim-edgemotion"
rev = "8d16bd92f6203dfe44157d43be7880f34fd5c060"

[plugins."accelerated-jk.nvim"]
git = "rainbowhxch/accelerated-jk.nvim"
rev = "8fb5dad4ccc1811766cebf16b544038aeeb7806f"

[plugins.vim-exchange]
git = "tommcdo/vim-exchange"
rev = "d6c1e9790bcb8df27c483a37167459bbebe0112e"

[plugins.overseer-quick-tasks]
git = "itsfrank/overseer-quick-tasks"
rev = "f3d0c1d29a04082feda51419d2466a3a7f3a7c3f"

[plugins."sibling-swap.nvim"]
git = "wansmer/sibling-swap.nvim"
rev = "269770df52114ed6f22321310538b4daf8973384"

[plugins.vim-smartq]
git = "marklcrns/vim-smartq"
rev = "v1.4.1"

[plugins."telescope-bookmarks.nvim"]
git = "dhruvmanila/telescope-bookmarks.nvim"
rev = "v4.0.0"

[plugins."zoxide.vim"]
git = "nanotee/zoxide.vim"
rev = "b1e70b6fc1682a83929aee63680d2b43456fe9a5"

[plugins."grug-far.nvim"]
git = "magicduck/grug-far.nvim"
rev = "e12bedbc0f216aebab8ca4b520760b96ba524022"

[plugins."ssr.nvim"]
git = "cshuaimin/ssr.nvim"
rev = "bb323ba621ac647b4ac5638b47666e3ef3c279e1"

[plugins."muren.nvim"]
git = "acksld/muren.nvim"
rev = "818c09097dba1322b2ca099e35f7471feccfef93"

[plugins.nvim-dd]
git = "yorickpeterse/nvim-dd"
rev = "9c21ffeffbf0a99e5614f193455700f355d0951f"

[plugins."troublesum.nvim"]
git = "ivanjermakov/troublesum.nvim"
rev = "b00301bb565bfcb6fcfa41f2012e43a0528da65b"

[plugins.better-diagnostic-virtual-text]
git = "sontungexpt/better-diagnostic-virtual-text"
rev = "eb3a77e714aa6c295bdb4f074fccbda637090f6e"

[plugins."mason-null-ls.nvim"]
git = "jay-babu/mason-null-ls.nvim"
rev = "v2.6.0"
opt = true

[plugins."none-ls-autoload.nvim"]
git = "zeioth/none-ls-autoload.nvim"
rev = "v1.0.0"
opt = true

[plugins."luasnip-latex-snippets.nvim"]
git = "iurimateus/luasnip-latex-snippets.nvim"
rev = "4b91f28d91979f61a3e8aef1cee5b7c7f2c7beb8"

[plugins.neorg-hop-extras]
git = "phenax/neorg-hop-extras"
rev = "f349ab3e9a52d214f1af6122cd087218b2722c81"


[plugins.neorg-exec]
git = "laher/neorg-exec"
rev = "90064eaeee596eb6ec1c476cf26ea0087861faed"

[plugins."refactoring.nvim"]
git = "theprimeagen/refactoring.nvim"
rev = "c406fc5fb4d7ba5fce7b668637075fad6e75e9f8"
opt = true

[plugins."python-copy-reference.vim"]
git = "ranelpadon/python-copy-reference.vim"
rev = "8172d0ce83d730820d9497fd2e988046022d0b99"
opt = true

[plugins."direnv.vim"]
git = "direnv/direnv.vim"
rev = "ab2a7e08dd630060cd81d7946739ac7442a4f269"
opt = true

[plugins."oil-image-preview.nvim"]
git = "mimikun/oil-image-preview.nvim"
rev = "b66731111c206f085c2b65a895637d30d676cc05"
opt = true

[plugins.abstract-autocmds]
git = "abstract-ide/abstract-autocmds"
rev = "d2e4cfd67cf59166f9ffa0bd3bc90899ffc653e7"

[plugins."fileline.nvim"]
git = "lewis6991/fileline.nvim"
rev = "c116aa8dd7aa7e1db6938f872285e598dc9ee00b"

[plugins."hlchunk.nvim"]
version = "1.1.0"
opt = true

[plugins."definition-or-references.nvim"]
git = "kostkabrukowa/definition-or-references.nvim"
rev = "13570f995be8993f4c55e988f89e5a7b8df37a17"

[plugins."diagnostic-window.nvim"]
git = "cseickel/diagnostic-window.nvim"
rev = "2b4d9618382502740c7945c4023853ee524adc4c"
opt = true


[plugins.cmp-nvim-lua]
git = "hrsh7th/cmp-nvim-lua"
rev = "f12408bdb54c39c23e67cab726264c10db33ada8"
opt = true


[plugins."copilot.lua"]
git = "zbirenbaum/copilot.lua"
rev = "86537b286f18783f8b67bccd78a4ef4345679625"
opt = true

[plugins."kanagawa-paper.nvim"]
git = "sho-87/kanagawa-paper.nvim"
rev = "v1.5.0"

[plugins."none-ls.nvim"]
version = "scm"
opt = true

[plugins."glance.nvim"]
version = "scm"
opt = true

[plugins."exemplum.nvim"]
git = "ntbbloodbath/exemplum.nvim"
rev = "8469ba46c860d4e2f5d5a929b92afd2421503d23"
opt = true

[plugins."avante.nvim"]
git = "yetone/avante.nvim"
rev = "main"
build = "make"

[plugins.nvim-rip-substitute]
git = "chrisgrieser/nvim-rip-substitute"
rev = "4e5ed58d74d210b853255e3d1a4ab6410f3007b5"
opt = true

[plugins."guihua.lua"]
git = "ray-x/guihua.lua"
rev = "v0.1^{}"

[plugins.auto-session]
git = "rmagatti/auto-session"
rev = "v2.5.0"

[plugins.neocord]
git = "iogamaster/neocord"
rev = "aa7a58023166533da83ca7b11c0d2569e45d7381"
opt = true

[plugins.nvim-treesitter-textobjects]
git = "nvim-treesitter/nvim-treesitter-textobjects"
rev = "a34d063932adab24234e85f35f5d3529d34c1c4c"
opt = true
branch = "main"

[plugins.vim-matchup]
git = "andymass/vim-matchup"
rev = "8522c9b3ba6c92ac64a609fa792134ce6ba9c4bc"
opt = true

[plugins."multicursors.nvim"]
git = "smoka7/multicursors.nvim"
rev = "main"
opt = true

[plugins."hydra.nvim"]
git = "nvimtools/hydra.nvim"
rev = "main"
opt = true

[plugins."edgy.nvim"]
version = "scm"
opt = true

[bundles.startup]
items = [
  "abstract-autocmds",
]


[bundles.completion] # Create a bundle called `lsp`
items = [
  "nvim-cmp",
  "cmp-path",
  "cmp_luasnip",
  "luasnip",
  "cmp-vimtex",
  "cmp-nvim-lsp",
  "friendly-snippets",
  "luasnip-snippets",
  "luasnip-latex-snippets.nvim",
  "nvim-autopairs",
  "neotab.nvim"
]

[bundles.lsp]
items = [
  "nvim-lspconfig",
  "mason-lspconfig.nvim",
  "mason.nvim",
  "lsp-command",
  "navigator.lua",
  "avante.nvim"
]

[bundles.ui]
items = [
  "dropbar.nvim",
  "heirline.nvim",
  "auto-session"
]


[bundles.test]
items = [
  "nvim-surround",
  "nvim-spider",
  "oil.nvim",
  "dmacro.nvim",
]

[bundles.search]
items = [
"telescope.nvim"
]

[config]
auto_setup = true
colorscheme = "kanagawa-paper"

[rocks_lazy]
import = "lazy_specs"
