std="lua51+vim"

[config]
empty_if = { comments_count = true }
unused_variable = { ignore_pattern = "result|ok|^_" }
shadowing = { ignore_pattern = "result|ok|^_" }

[rules]
global_usage = "allow"
unused_variable = "allow"
shadowing = "allow"

if_same_then_else = "allow"