-- path = "/home/viv/.luarocks/lib/lua/5.1/yaml.so"
-- if vim.fn.filereadable(path) == 0 then
--     print("yaml.so not found")
--     return
-- else
--     package.cpath = package.cpath .. ";" .. path
--     require("lyaml")
-- end
