vim.cmd([[
" Syntax.
inoreabbrev asycn     async
inoreabbrev cosnt     const
inoreabbrev ehco      echo
inoreabbrev flase     false
inoreabbrev functoin  function
inoreabbrev ocnst     const
inoreabbrev retunr    return
inoreabbrev reutnr    return
inoreabbrev reutrn    return
inoreabbrev strign    string
inoreabbrev treu      true
inoreabbrev undefiend undefined

" English words.
inoreabbrev teh       the
inoreabbrev Adn       And
inoreabbrev adn       and
inoreabbrev Execture  Execute
inoreabbrev execture  execute
inoreabbrev Exectures Executes
inoreabbrev exectures executes
inoreabbrev Nubmer    Number
inoreabbrev nubmer    number
inoreabbrev Nubmers   Numbers
inoreabbrev nubmers   numbers
inoreabbrev Reponse   Response
inoreabbrev reponse   response
inoreabbrev Reponses  Responses
inoreabbrev reponses  responses
inoreabbrev Resovle   Resolve
inoreabbrev resovle   resolve
inoreabbrev Resovled  Resolved
inoreabbrev resovled  resolved
inoreabbrev Resovles  Resolves
inoreabbrev resovles  resolves
inoreabbrev Resovling Resolving
inoreabbrev resovling resolving
inoreabbrev Serach    Search
inoreabbrev serach    search
inoreabbrev Serached  Searched
inoreabbrev serached  searched
inoreabbrev Seraches  Searches
inoreabbrev seraches  searches
inoreabbrev Seraching Searching
inoreabbrev seraching searching
inoreabbrev Shuold    Should
inoreabbrev shuold    should
inoreabbrev Soruce    Source
inoreabbrev soruce    source
inoreabbrev Soruces   Sources
inoreabbrev soruces   sources
inoreabbrev Sorucing  Sourcing
inoreabbrev sorucing  sourcing
inoreabbrev udner     under
inoreabbrev Udner     Under
inoreabbrev Udpate    Update
inoreabbrev udpate    update
inoreabbrev Udpated   Updated
inoreabbrev udpated   updated
inoreabbrev Udpates   Updates
inoreabbrev udpates   updates
inoreabbrev Udpating  Updating
inoreabbrev udpating  updating
inoreabbrev Widnow    Window
inoreabbrev widnow    window
inoreabbrev WidnoWing Windowing
inoreabbrev widnowing windowing
inoreabbrev Widnows   Windows
inoreabbrev widnows   windows

inoreabbrev rtfm read the fucking manual
]])
