local config = {}
function config.abbrv()
    local abbrev_man = require("abbrev-man")

    abbrev_man.setup({
        load_natural_dictionaries_at_startup = true,
        load_programming_dictionaries_at_startup = true,
        natural_dictionaries = {
            ["nt_en"] = {
                ["asycn"] = "async",
                ["cosnt"] = "const",
                ["ehco"] = "echo",
                ["flase"] = "false",
                ["functoin"] = "function",
                ["ocnst"] = "const",
                ["retunr"] = "return",
                ["reutnr"] = "return",
                ["reutrn"] = "return",
                ["strign"] = "string",
                ["treu"] = "true",
                ["undefiend"] = "undefined",
                ["teh"] = "the",
                ["Teh"] = "The",
                ["Adn"] = "And",
                ["adn"] = "and ",
                ["Execture"] = "Execute",
                ["execture"] = "execute",
                ["Exectures"] = "Executes",
                ["exectures"] = "executes",
                ["Nubmer"] = "Number",
                ["nubmer"] = "number",
                ["Nubmers"] = "Numbers",
                ["nubmers"] = "numbers",
                ["Reponse"] = "Response",
                ["reponse"] = "response",
                ["Reponses"] = "Responses",
                ["reponses"] = "responses",
                ["Resovle"] = "Resolve",
                ["resovle"] = "resolve",
                ["Resovled"] = "Resolved",
                ["resovled"] = "resolved",
                ["Resovles"] = "Resolves",
                ["resovles"] = "resolves",
                ["Resovling"] = "Resolving",
                ["resovling"] = "resolving ",
                ["Serach"] = "Search",
                ["serach"] = "search",
                ["Serached"] = "Searched",
                ["serached"] = "searched",
                ["Seraches"] = "Searches",
                ["seraches"] = "searches",
                ["Seraching"] = "Searching",
                ["seraching"] = "searching",
                ["Shuold"] = "Should",
                ["shuold"] = "should",
                ["Soruce"] = "Source",
                ["soruce"] = "source",
                ["Soruces"] = "Sources",
                ["soruces"] = "sources",
                ["Sorucing"] = "Sourcing",
                ["sorucing"] = "sourcing",
                ["udner"] = "under",
                ["Udner"] = "Under",
                ["Udpate"] = "Update",
                ["udpate"] = "update",
                ["Udpated"] = "Updated",
                ["udpated"] = "updated",
                ["Udpates"] = "Updates",
                ["udpates"] = "updates",
                ["Udpating"] = "Updating",
                ["udpating"] = "updating",
                ["Widnow"] = "Window",
                ["widnow"] = "window",
                ["WidnoWing"] = "Windowing   ",
                ["widnowing"] = "windowing",
                ["Widnows"] = "Windows",
                ["widnows"] = "windows",
                ["rtfm"] = "the fucking manual",
            },
        },
    })
end

return config
