return {
    lambda.config.python.lint,
    "cppcheck",
    "djlint",
    "eslint_d",
    "golangci_lint",
    "ktlint",
    "markdownlint",
    "misspell",
    "mypy",
    "phpcs",
    "pylint",
    "revive",
    "shellcheck",
    "staticcheck",
    "stylelint",
    "write_good",
    "luacheck",
    -- "semgrep",
}
